name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - run: docker login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
      - uses: actions/checkout@v3
      - run: docker build --tag ghcr.io/hfhbd/miktex .
      - run: docker push ghcr.io/hfhbd/miktex
